### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known 

### ISSUE THREAD

**Issue by ocharykov** [esrlabs/northstar#447]
Hello,
Could you please advise how to config the container to avoid problems with DNS?

we could not reach from container external resource by name and see an error 

`socket.gaierror: [Errno -2] Name or service not known `

Could you please advise some solution? 
Thank you!

**Comment by flxo** [comment]
Hello @ocharykov 

Without any context about your setup probably not.

I'd recommend to use strace to see which sys call raised the -2. Probably you haven't provided a proper dns setup for your container. Depending on the libc implementation you might needs stuff from `/etc`.

cheers,
Felix

**Comment by ocharykov** [comment]
```
2021-10-19T11:01:20.095Z: INFO : runtime::state Started mycontainer:0.0.1 (4849) in 0.477s
2021-10-19T11:01:20.095Z: DEBUG: runtime::island::io stdout: Rust part start here --->
2021-10-19T11:01:20.108Z: INFO : runtime::console 127.0.0.1:45936: Connection closed
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout: status: exit status: 1
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout: stdout: ---------------------------------------
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout: Python part start here.
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout: ---------------------------------------
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout: 
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout: stderr: Traceback (most recent call last):
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout:   File "/test/hello.py", line 32, in <module>
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout:     main()
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout:   File "/test/hello.py", line 10, in main
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout:     print(socket.gethostbyname('security.ubuntu.com'))
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout: socket.gaierror: [Errno -2] Name or service not known
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout: 
2021-10-19T11:01:21.182Z: DEBUG: runtime::island::io stdout: Rust part end here --->
2021-10-19T11:01:21.182Z: DEBUG: runtime::debug mycontainer: wait4(2, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], __WALL, NULL) = 2
2021-10-19T11:01:21.182Z: DEBUG: runtime::debug mycontainer: sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
2021-10-19T11:01:21.182Z: DEBUG: runtime::debug mycontainer: munmap(0x7fe696619000, 12288)           = 0
2021-10-19T11:01:21.182Z: DEBUG: runtime::debug mycontainer: exit_group(0)                           = ?
2021-10-19T11:01:21.205Z: DEBUG: runtime::debug mycontainer: +++ exited with 0 +++
```
I hope it is clear for you

**Comment by ocharykov** [comment]
[strace-5055-mycontainer.strace.txt](https://github.com/esrlabs/northstar/files/7372702/strace-5055-mycontainer.strace.txt)
Full logs

**Comment by ocharykov** [comment]
```
2021-10-19T12:29:13.800Z: DEBUG: runtime::console Client 127.0.0.1:45992 connected
2021-10-19T12:29:13.801Z: INFO : runtime::state Trying to start mycontainer:0.0.1
2021-10-19T12:29:13.801Z: INFO : runtime::state Need to mount 0 container before starting mycontainer:0.0.1
2021-10-19T12:29:13.801Z: INFO : runtime::state Creating mycontainer:0.0.1
2021-10-19T12:29:13.801Z: DEBUG: runtime::island::fs Mounting /proc
2021-10-19T12:29:13.801Z: DEBUG: runtime::island::fs Mounting /lib on /lib with []
2021-10-19T12:29:13.801Z: DEBUG: runtime::island::fs Mounting target/northstar/run/python3:0.0.1/python3 on /python3 with {NoSuid, NoDev}
2021-10-19T12:29:13.801Z: DEBUG: runtime::island::fs Mounting /etc on /etc with [Rw]
2021-10-19T12:29:13.801Z: DEBUG: runtime::island::fs Mounting /home/developer on /test with [Rw]
2021-10-19T12:29:13.801Z: DEBUG: runtime::island::fs Mounting /usr on /usr with [Rw]
2021-10-19T12:29:13.801Z: DEBUG: runtime::island::fs Mounting /lib64 on /lib64 with []
2021-10-19T12:29:13.802Z: DEBUG: runtime::island::fs Creating devfs in /tmp/.tmp0PIqIO
2021-10-19T12:29:13.808Z: DEBUG: runtime::island mycontainer init is "/mycontainer"
2021-10-19T12:29:13.808Z: DEBUG: runtime::island mycontainer argv is ["/mycontainer", "/python3/bin"]
2021-10-19T12:29:13.808Z: DEBUG: runtime::island mycontainer env is ["NAME=mycontainer", "VERSION=0.0.1", "LD_LIBRARY_PATH=/lib"]
2021-10-19T12:29:13.809Z: DEBUG: runtime::island Created mycontainer:0.0.1 with pid 5555
2021-10-19T12:29:13.816Z: INFO : runtime::island Starting 5555
2021-10-19T12:29:13.820Z: INFO : runtime::state Started mycontainer:0.0.1 (5555) in 0.019s
2021-10-19T12:29:13.821Z: DEBUG: runtime::island::io stdout: Rust part start here --->
2021-10-19T12:29:13.824Z: INFO : runtime::console 127.0.0.1:45992: Connection closed
2021-10-19T12:29:14.209Z: DEBUG: runtime::island::io stdout: status: exit status: 1
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout: stdout: ---------------------------------------
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout: Python part start here.
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout: ---------------------------------------
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout: 
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout: stderr: Traceback (most recent call last):
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout:   File "/test/hello.py", line 32, in <module>
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout:     main()
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout:   File "/test/hello.py", line 10, in main
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout:     print(socket.gethostbyname('security.ubuntu.com'))
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout: socket.gaierror: [Errno -2] Name or service not known
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout: 
2021-10-19T12:29:14.210Z: DEBUG: runtime::island::io stdout: Rust part end here --->
2021-10-19T12:29:14.210Z: DEBUG: runtime::debug mycontainer: wait4(2, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], __WALL, NULL) = 2
2021-10-19T12:29:14.211Z: DEBUG: runtime::debug mycontainer: sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
2021-10-19T12:29:14.211Z: DEBUG: runtime::debug mycontainer: munmap(0x7fc0e0582000, 12288)           = 0
2021-10-19T12:29:14.213Z: DEBUG: runtime::debug mycontainer: exit_group(0)                           = ?
2021-10-19T12:29:14.222Z: DEBUG: runtime::debug mycontainer: +++ exited with 0 +++
2021-10-19T12:29:14.223Z: DEBUG: runtime::island Process 5555 exit code is 0
2021-10-19T12:29:14.223Z: INFO : runtime::state Process mycontainer:0.0.1 exited after 402.271537ms with status Exit(0)
2021-10-19T12:29:14.223Z: DEBUG: runtime::debug Joining strace pid 5556

```
